spring:
  application:
    name: kafkaserver
  kafka:
    bootstrap-servers: code-factory.co.kr:3450 # Kafka ???(?? ????) ?? ??? ??, ??(,)? ?? ??? ?? ??
    consumer:
      group-id: sparta-group # ??? ?? ID: ?? ??? ?? ????? ???? ???? ??
      auto-offset-reset: earliest # ???? ?? ??? ? ???? ??? ????? ??? ??, earliest: ?? ???(??) ?????, latest: ?? ??? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # ??? ? ?????(???? ???)
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # ??? ? ?????(JSON -> ??)
      properties:
        spring.json.trusted.packages: '*' # JsonDeserializer? ??? ??? ??, '*' ?? ???? ??(??? ??? ??? ??? ?? ???? ??)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? ? ???
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # ??? ? ???(?? -> JSON)
      properties:
        spring.json.add.type.headers: true